### ISSUE TITLE
Tratamento (TryException) para o "Motivo"

### ISSUE THREAD

**Issue by andersonraymundosouza** [deguedess/IPAA#3]
Fazer tratamento para o erro, caso não tenha "Motivo" cadastrado.

**Comment by deguedess** [comment]
Adicionado validação para caso não haja motivo, seja feito o cadastro.

def getMotivos(nomeMotivo):

        try:
            return Motivo.objects.get(nome=nomeMotivo)
        except Exception as e:
            motivo = Motivo()
            motivo.nome = nomeMotivo
            motivo.save()
            return motivo
