### ISSUE TITLE
Carteira Manual sem marcar

### ISSUE THREAD

**Issue by andersonraymundosouza** [deguedess/IPAA#4]
Quando não marco nenhuma opção das recomendações na vez da Carteira 'Manual', o IPAA não gera nada nenhum dado no Histórico de Carteiras.
Acredito que deveria gerar:
Verde: Recomendação IA
Vermelho: Seguiu Recomendação 
Opção de compra (pois deixei tudo desmarcado)

Ou a lógica que tu quis seguir foi:
Na recomendação manual, na primeira vez, se não marcar nada quer dizer que  "Não seguiu recomendação" e também não teve alteração de carteira.. Daí nas próximas iterações aí sim gerar operações de Compra e Venda.. Daí a lógica ta certa.

**Comment by deguedess** [comment]
Ajustado validação na tela de portfolio.
